### ISSUE TITLE
Setting max listener count

### ISSUE THREAD

**Issue by Dabada** [sindresorhus/component-emitter#68]
Hi,
Is there a way to set a setMaxListeners for you Emitter object ? Standard Node Js EventEmitter provides the function setMaxListeners(). It's a very useful function. It allows me to detect memory leaks when the same listener is attached to the Emitter more than once.

Thank's for you great work. It's a very nice and useful library !

**Comment by GrosSacASac** [comment]
One of the purpose of such a library is to be as lightweight as possible. For extra runtime checks, search for event emitter, there are alternatives that mimic NodeJs API 1 to 1.

**Comment by sindresorhus** [comment]
This is outside the scope of this package.
