### ISSUE TITLE
Please document which npm package is the one you update

### ISSUE THREAD

**Issue by psnider** [sindresorhus/component-emitter#78]
There are two npm packages that are tied to this git repo:
- https://www.npmjs.com/package/component-emitter  
  This one is at version 1.2.1, with 250k downloads/day  
  and appears to be the active one.
- https://www.npmjs.com/package/emitter-component  
  This one is at version 1.1.1, with 6k downloads/day  
  Please mark this one as unmaintained,  
  with a comment directing people to use **component-emitter** instead.

**Comment by sindresorhus** [comment]
I have deprecated `emitter-component`.
