### ISSUE TITLE
npm documentation is wrong

### ISSUE THREAD

**Issue by mmontag** [sindresorhus/component-emitter#81]
`$ component install component/emitter` should be `$ npm install component-emitter`.

Commenting as someone who has no idea what 'Component' is.

**Comment by seanohue** [comment]
I agree that the npm docs should include npm installation directions, also: http://smalljs.org/package-managers/component-part-1/

**Comment by seanohue** [comment]
(alternatively, include the above link or similar explanation, since googling 'javascript component cli' mostly shows Angular stuff these days)

**Comment by vendethiel** [comment]
It probably should show npm nowadays, yes.

**Comment by sindresorhus** [comment]
Fixed
