### ISSUE TITLE
Emitter Component > Failing License Check

### ISSUE THREAD

**Issue by viveksacademia4git** [sindresorhus/component-emitter#87]
The Emitter Component is Failing License Check.  
Please refer to the [Issue-1](https://github.com/viveksacademia4git/emitter-component-test/issues/1) created within the [emitter-component-test](https://github.com/viveksacademia4git/emitter-component-test) GitHub Repository.

**Comment by viveksacademia4git** [comment]
Any update on this?

**Comment by phil294** [comment]
I can confirm this issue. Not really sure why this happens, as this repository clearly has a LICENSE file. But here's my project  output:

`yarn license-checker --production --summary`:
```
├─ MIT: 181
├─ ISC: 61
├─ BSD-2-Clause: 6
├─ Apache-2.0: 4
├─ MIT*: 3
├─ BSD-3-Clause: 2
├─ (Apache-2.0 OR MIT): 2
├─ MPL-2.0 OR Apache-2.0: 1
├─ Custom: https://travis-ci.org/component/emitter.png: 1
├─ (MIT AND Zlib): 1
├─ (BSD-2-Clause OR MIT OR Apache-2.0): 1
└─ (MIT OR CC0-1.0): 1
```
And digging deeper, `yarn license-checker --production`: 
```
[...]
├─ emitter-component@1.1.1
│  ├─ licenses: Custom: https://travis-ci.org/component/emitter.png
│  ├─ repository: https://github.com/component/emitter
│  ├─ path: /b/ei/ef2/repo/web/web/node_modules/emitter-component
│  └─ licenseFile: /b/ei/ef2/repo/web/web/node_modules/emitter-component/Readme.md
[...]
```

**Comment by viveksacademia4git** [comment]
The license is available in the GitHub Repository but I did not find it in the YARN or NPM package.  
I even checked physically, it is not there. Maybe if you can put the file in the library and republish the package on Node Package Manager then it should resolve.

**Comment by viveksacademia4git** [comment]
See the output:
```
$ git clone https://github.com/viveksacademia4git/emitter-component-test

$ yarn install

$ dir node_modules/emitter-component/
bower.json  component.json  History.md	index.js  Makefile  package.json  Readme.md  test
```

Like I said the file does not exist

**Comment by sindresorhus** [comment]
Fixed

**Comment by FFelt** [comment]
Sorry to maybe reopen this old issue, but the emitter-component still has no license in the package.

See: https://www.npmjs.com/package/emitter-component

Could you please provide a license there?

I've seen the component-emitter has the MIT License, but I'm using a library which has a dependency to another library, which then still uses emitter-component. Therefore, I can't easily change the packages.

Thanks in advance.
