### ISSUE TITLE
Just some random questions

### ISSUE THREAD

**Issue by TannerS** [sindresorhus/component-emitter#94]
I am trying to learn more about this library but i had some questions. 

well in all honesty, i am a little lost on how this works.

1) If i take this example in the Readme

```
import Emitter from 'component-emitter';

const emitter = new Emitter();

emitter.emit('🦄');
```

If i understand correctly, you can create a new Emitter and register listeners to it. When you do, you create it with an event type. then using emit, you pass in that event type. then some listners like `Emitter#on` will run what ever you pass in

is that correct so far?

2) To follow up, may i ask for an explanation on this example

```
import Emitter from 'component-emitter';

Emitter(User.prototype);

```

what does this do ? does it mean it uses the passed in object as a way to detect for events?  I found another library that used the prototype of an advance nodejs class into the `component-emitter` constructor, but i am not sure what changes that vs an empty create of a `component-emitter` instance. 

thanks in advance!

**Comment by TannerS** [comment]
follow up, in this line `https://github.com/sindresorhus/component-emitter/blob/cfa15e8a6382f4403fb8b05f9c363ae997eb171c/index.js#L77` when u set the prototype method, is that two your own function on line 1 or the built in Emitter class for node?

sorry im learning more js/node so i ran into this. but why use prototype anyways?

**Comment by sindresorhus** [comment]
Your understanding of `component-emitter` is on the right track. Let's clarify your queries:

1. **Emitter Functionality**: Yes, you've got the basic idea. `component-emitter` allows you to create an emitter object which can emit events. You can then use `Emitter#on` to listen for these events. When you emit an event using `emitter.emit('event')`, any functions registered with `emitter.on('event', function)` get executed.

2. **Using `Emitter` with `User.prototype`**: The `Emitter(User.prototype)` pattern is about mixing in Emitter methods into another object, in this case, `User.prototype`. This means all instances of `User` inherit the event emitter capabilities. It's a way to extend a class with event emitter functionality without using inheritance.

3. **Prototype Usage**: The use of `prototype` in JavaScript is a fundamental concept for object-oriented programming in the language. By setting methods on a prototype, all instances of that object share the same method, saving memory and allowing for shared functionality. It's a common pattern in JavaScript to extend objects' capabilities.

4. **Prototype Method at Line 77**: The code at the specified GitHub link is assigning a function to the prototype of the `Emitter`. It's not a built-in Node.js method but one defined within the `component-emitter` package. This method becomes available to all instances of objects that use `Emitter`.

5. **Why Use Prototype**: Using prototypes is a core part of JavaScript's object-oriented approach. It allows for efficient memory usage and shared behavior across instances. It's especially useful when you want to extend the functionality of existing classes or objects without modifying them directly.

In essence, `component-emitter` gives you a lightweight way to add event emitting and listening capabilities to any object in Node.js, leveraging JavaScript's prototype-based inheritance.
